version: '3'
services:
  clubs-app:
    build: .
    ports:
      - "9000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_DATABASE=value
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123@Password
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: