/*SUPPRIMER LA BD clubs S'ELLE EXISTE DANS NOTRE SGBD*/
DROP DATABASE IF EXISTS clubs;

/*CREATION D'UNE SEQUENCE POUR L'ID DE user*/

CREATE SEQUENCE user_id START WITH 1 INCREMENT BY 1;

/*CREATION D'UNE SEQUENCE POUR L'ID DE L'APPRENANT*/

CREATE SEQUENCE apprenant_id START WITH 1 INCREMENT BY 1;

/*CREATION D'UNE SEQUENCE POUR L'ID DE CLUB*/

CREATE SEQUENCE club_id START WITH 1 INCREMENT 1;

